// Code generated by sqlc. DO NOT EDIT.

package db

import (
	"time"
)

type CurrencyRate struct {
	CurrencyCode string    `json:"currency_code"`
	Rate         int64     `json:"rate"`
	ValidDate    time.Time `json:"valid_date"`
}

type User struct {
	ID       string `json:"id"`
	Email    string `json:"email"`
	UserName string `json:"user_name"`
	City     string `json:"city"`
	Country  string `json:"country"`
}

type Wallet struct {
	ID           string `json:"id"`
	CurrencyCode string `json:"currency_code"`
	Amount       int64  `json:"amount"`
	UserID       string `json:"user_id"`
}

type WalletOperation struct {
	ID       int64  `json:"id"`
	WalletID string `json:"wallet_id"`
	// amount in wallet currency
	Amount int64 `json:"amount"`
	// amount in USD
	AmountUsd int64 `json:"amount_usd"`
	// amount in operation currency
	AmountOperation int64 `json:"amount_operation"`
	// currency operation
	CurrencyCode string    `json:"currency_code"`
	CreateAt     time.Time `json:"create_at"`
}
