// Code generated by sqlc. DO NOT EDIT.

package db

import (
	"context"
)

type Querier interface {
	AddUserBalance(ctx context.Context, arg AddUserBalanceParams) error
	ChangeCurrencyRate(ctx context.Context, arg ChangeCurrencyRateParams) error
	CreateUser(ctx context.Context, arg CreateUserParams) error
	CreateWallet(ctx context.Context, arg CreateWalletParams) error
	CreateWalletOperation(ctx context.Context, arg CreateWalletOperationParams) error
	GetCurrencyRate(ctx context.Context, arg GetCurrencyRateParams) (int64, error)
	GetSumWalletOperation(ctx context.Context, arg GetSumWalletOperationParams) (GetSumWalletOperationRow, error)
	GetUser(ctx context.Context, id string) (User, error)
	GetWalletByUser(ctx context.Context, userID string) (Wallet, error)
	GetWalletByUserForUpdate(ctx context.Context, userID string) (Wallet, error)
	GetWalletOperationList(ctx context.Context, arg GetWalletOperationListParams) ([]WalletOperation, error)
	ReduceUserBalance(ctx context.Context, arg ReduceUserBalanceParams) error
}

var _ Querier = (*Queries)(nil)
